# this is the file used by docker-compose to launch ethercalc
# to start ethercalc: sudo docker-compose -f ./ethercalc-compose.yml up -d
# to stop  ethercalc: sudo docker-compose -f ./ethercalc-compose.yml down

# EtherCalc REST API docs: http://docs.ethercalc.apiary.io/ or https://github.com/audreyt/ethercalc/blob/master/API.md
# EtherCalc home: https://ethercalc.net/
# EtherCalc GitHub: https://github.com/audreyt/ethercalc
# EtherCalc Docker: https://hub.docker.com/r/audreyt/ethercalc/
# docker-compose reference: https://docs.docker.com/compose/

# Launch galaxy in a Docker container
galaxy:
  security_opt:
    - label:user:${DOCKER_USER}
  # for some reason, cap_drop all causes the galaxy container to infinitely restart
  # cap_drop:
  #   - ALL
  # image: workflow4metabolomics/galaxy-workflow4metabolomics
  # image: workflow4metabolomics/galaxy-workflow4metabolomics:release-2.5.1.3
  image: eschen42/w4m
  ports:
    - "9080:80"
    - "9021:21"
  volumes:
    - ${GALAXY_COMPOSE_DIR}/export:/export/
  environment:
    - GALAXY_CONFIG_REQUIRE_LOGIN=True
    # I am not using condor right now, so I am switching it off here.
    #   But also note that for Galaxy 16.07, condor 8.4.8-373513-ubuntu14 is listed as a high security vulnerability at
    #     https://quay.io/repository/bgruening/galaxy/image/17ee75162915f5fcc8a61ca4ca538a492e9648dbbc479cf166458c4ab34c4ae1?tab=vulnerabilities
    - NONUSE=condor
    # TODO update admin user identifier(s); this is a comma-separated list
    - GALAXY_CONFIG_ADMIN_USERS=you@somedomain
    # TODO update brand
    - GALAXY_CONFIG_BRAND='unbranded W4M'
    # - GALAXY_CONFIG_MASTER_API_KEY=32-hexadecimal-lowercase-characters-used-for-bootstrapping-galaxy
  links:
    - redis
  restart: always

# Launch ethercalc in a Docker container
ethercalc:
  security_opt:
    - label:user:${DOCKER_USER}
  cap_drop:
    - ALL
  #image: audreyt/ethercalc
  image: eschen42/ethercalc
  ports:
    - "8000:8000"
  links:
    - redis
  restart: always

# Launch redis in another Docker container to serve as the datastore for ethercalc
redis:
  security_opt:
    - label:user:${DOCKER_USER}
  # for some reason, cap_drop all causes the redis-server container to infinitely restart
  # cap_drop:
  #   - ALL
  image: redis:latest
  # volumes:
  #   - /var/lib/redis:/data
  command: redis-server --appendonly yes
  restart: always

# Note that eschen42/ethercalc was built using:
#  - this command: sudo docker build -t eschen42/ethercalc -f ./DockerFile . 
#  - the following ./DockerFile contents:
# FROM node:4.4
# 
# RUN useradd ethercalc --create-home
# RUN npm install -g ethercalc pm2
# 
# USER ethercalc
# ENV HOME /home/ethercalc
# EXPOSE 8000
# CMD ["sh", "-c", "REDIS_HOST=$REDIS_PORT_6379_TCP_ADDR REDIS_PORT=$REDIS_PORT_6379_TCP_PORT pm2 start -x `which ethercalc` -- && pm2 logs"]

